# gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.java.installations.auto-download=false

# minecraft
minecraft_version=1.12.2

# forge
forge_gradle_version=6.0.+
forge_version=14.23.5.2864
mappings_channel=stable
mappings_version=39-1.12
fancy_gradle_version=1.1.+

# mixin
mixin_gradle_version=0.7.+
mixin_version=0.8.7
mixin_extras_version=0.5.0

# mod
mod_id=bettersnowvillages
mod_name=Better Snow Villages
mod_version=0.0.0
mod_author=["cdstk"]
mod_description=Better Ice And Fire Snow Villages
mixin_loader_class=bettersnowvillages.BetterSnowVillagesPlugin

# dependencies
fermiumbooter_version=968474:8683582

# primary inf version
llibrary_version=243298:2504999
iceandfirerlc_version=888556:8350620
# forks
iceandfirerotn_version=457668:5738729
iceandfire_version=264231:2693547

# compat
waystones_version=245755:2859589
forgelin_version=248453:2785465
bountiful_version=309516:3570157
ivtoolkit_version=224535:2443253
recurrentcomplex_version=223150:8562927
quark_version=243121:2924091
charm_version=318872:3146596
antiqueatlas_version=227795:2823030
aaam_version=1195708:7922517